### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ssill2**
Fixing some formatting because I'm a github n00b :)

### CODE REVIEW

**Comment by ldthomas** [comment]
:) Yeah, I noticed. But don't feel bad. It is sometimes hard to tell how GitHub will render the .md file. I also added a note to the master branch README.md pointing out that the new maven branch was there.

**Comment by ldthomas** [comment]
Humm? Still not right. Let me take a shot at it.

**Comment by ssill2** [comment]
doh! sorry!

**Comment by ssill2** [comment]
Oh I see it now.  Sorry I was working on three things lol.   Let me know of you change it and I'll pull.   Otherwise I can fix it up and submit another PR.

**Comment by ldthomas** [comment]
I'm working on it. Got a short errand to run but I'll be back shortly.

**Comment by ssill2** [comment]
cool thanks!

**Comment by ldthomas** [comment]
Try it now. A good resource is [StackEdit](https://stackedit.io/). Not always a 100% but always a good start.

**Comment by ssill2** [comment]
ah cool thank you!

**Comment by ssill2** [comment]
looks great.  Thanks again.

**Pull request merged**
